### ISSUE TITLE
firebase database recreation

### ISSUE THREAD

**Issue by FJLopezGarcia** [eellak/conference-app#2]
How i can recreate the database in firebase? please help

**Comment by LeoLoupos** [comment]
Hello @FJLopezGarcia 

You can see our latest JSON import to the Firebase server , to the link below .
https://jsonblob.com/570f6c5b-53d8-11e8-85b4-33d171259487

Thanks Leonidas.

**Comment by FJLopezGarcia** [comment]
Thanks a lot!!
